# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Install build dependencies required for better-sqlite3
RUN apk add --no-cache python3 make g++

# Force npm to build native addons from source
ENV npm_config_build_from_source=true

# Create app directory
WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the code
COPY . ./

# Build the project and rebuild better-sqlite3 from source
RUN npm run build && npm rebuild better-sqlite3 --build-from-source

# The server currently runs on stdio for MCP communication. For WebSocket or HTTP support,
# you may need to set an environment variable or expose a port. Here, we assume the server
# listens on stdio and uses process.stdout/stdin for JSON-RPC communication.

CMD [ "node", "dist/index.js" ]
